apiVersion: v1
kind: Service
metadata:
  name: {{ include "siprproxy.fullname" . }}-registrar
  labels:
    {{- include "siprproxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - port: {{ .Values.service.registrarPort }}
      protocol: UDP
      name: sip-reg-udp
    - port: {{ .Values.service.registrarPort }}
      protocol: TCP
      name: sip-reg-tcp
  selector:
    {{- include "siprproxy.selectorLabels" . | nindent 4 }}
