apiVersion: v1
kind: Service
metadata:
  name: {{ include "sipproxy.fullname" . }}-sip
  labels:
    {{- include "sipproxy.labels" . | nindent 4 }}
spec:
  # type: ClusterIP
  type: NodePort
  # clusterIP: None # headless service
  # publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.sipPort }}
      protocol: UDP
      name: sip-udp
      nodePort: {{ .Values.service.sipPort }}
    - port: {{ .Values.service.sipPort }}
      protocol: TCP
      name: sip-tcp
      nodePort: {{ .Values.service.sipPort }}
  selector:
    {{- include "sipproxy.selectorLabels" . | nindent 4 }}
    app: sipproxy
