apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sipproxy.fullname" . }}
  labels:
    {{- include "sipproxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sipproxy.selectorLabels" . | nindent 6 }} # has to match .spec.template.metadata.labels
      app: sipproxy
  serviceName: {{ include "sipproxy.fullname" . }}-registrar # has to match headless Service metadata.name (added later, so not sure)
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sipproxy.selectorLabels" . | nindent 8 }} # has to match .spec.selector.matchLabels
        app: sipproxy
        # {{- include "sipproxy.labels" . | nindent 8 }}
        # {{- with .Values.podLabels }}
        # {{- toYaml . | nindent 8 }}
        # {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      subdomain: {{ include "sipproxy.fullname" . }}-registrar
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sip-tcp
              containerPort: {{ .Values.service.sipPort }}
              protocol: TCP
            - name: sip-udp
              containerPort: {{ .Values.service.sipPort }}
              protocol: UDP
            - name: sip-reg-tcp
              containerPort: {{ .Values.service.registrarPort }}
              protocol: TCP
            - name: sip-reg-udp
              containerPort: {{ .Values.service.registrarPort }}
              protocol: UDP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: [ {{ .Values.container.command | quote }}, {{ .Values.container.command1 | quote }}, {{ .Values.container.command2 | quote }} ]
          args: [ {{ .Values.container.args | quote }} ]
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
